Sort question bank / question list questions by most recently modified
civiform/civiform pull request #3359
Opened 2022-09-07 17:14 UTC by clouser2

### Description

Please explain the changes you made here.

## Release notes:

Describe the change as it should be communicated to partners in the release notes.

### Checklist

- [ ] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)

Fixes #<issue_number>; Fixes #<issue_number>; Fixes #<issue_number>...

2022-09-07 19:51 UTC, clouser2 commented on browser-test/src/civiform_admin_question_list.test.ts
> +describe('Most recently updated question is at top of list.', () => {
Note to the reviewer: This test was modeled off of the corresponding admin_program_list.test.ts (https://github.com/civiform/civiform/blob/08868c0bc54327e3ed4289c9827ba5c471f109e8/browser-test/src/admin_program_list.test.ts)

2022-09-07 21:35 UTC, nbeloglazov requested changes

2022-09-07 21:35 UTC, nbeloglazov commented on browser-test/src/civiform_admin_question_list.test.ts
> +    // Note: CI tests already have test questions
Is that true? Each test file starts with empty database. And if you have emptry database you can assume only your questions are present and simplify assertions below.

2022-09-07 21:35 UTC, nbeloglazov commented on browser-test/src/support/admin_programs.ts
> +  async questionBankNames(programName: string) {
Add return type `string[]` given that it's public function.

2022-09-07 21:35 UTC, nbeloglazov commented on browser-test/src/support/admin_questions.ts
> +  async questionNames() {
Same here.

2022-09-07 21:35 UTC, nbeloglazov commented on server/app/assets/javascripts/sorting.ts
> +  }
Looks like all these 3 blocks are mostly the same except for the selector. Maybe do process them in a loop?

```
for (const selector of ['.cf-admin-question-list', ...]) {
  const el = document.querySelector(selector);
  if (!el) continue;
  ...
}
```

2022-09-07 21:35 UTC, nbeloglazov commented on server/app/assets/javascripts/sorting.ts
> +      parent.classList.remove('invisible')
That makes me a bit nervous that we rely on JS to make element visible. So if JS is slow to load user will see empty page. I think ideally we'd want to sort server-side and add ability to re-sort client-side if necessary. But it's more work to maintain both server-side and client-side sorting... Do we expect other client-side sorting options to be added soon?

2022-09-09 21:57 UTC, clouser2 commented
This surfaced some existing issues where we weren't properly awaiting scripts after clicking a button which would trigger a navigation. While I rework things, I'll take it out of review.

2022-09-15 20:18 UTC, clouser2 reviewed
Replying to comments for posterity. This PR is being dropped in favor of https://github.com/civiform/civiform/pull/3431 (where all feedback has been incorporated). We'll now do sorting server-side until we have a real need for client-side sorting.

2022-09-15 20:19 UTC, closed without merging