Closes #816: Add maxlength to all input fields.
civiform/civiform pull request #3753
Opened 2022-11-02 20:35 UTC by ckirksey3

### Description

I add a maxlength HTML attribute to all LabelTags with a set length of 10,000 characters. This should reduce the likelihood of users submitting responses so large that the form post fails.

The attribute will exist on tag types for which it doesn't make sense (like checkboxes), but this seemed the cleanest way to achieve the protection given the current layout of the code and I don't believe the superfluous attribute will have any effect.

## Release notes:

Enforce max length of 10,000 characters on input fields.

### Checklist

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [x] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

#### User visible changes

- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/application.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://docs.civiform.us/contributor-guide/developer-guide/feature-flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Issue(s) this completes

Fixes #816;

2022-11-02 22:03 UTC, nbeloglazov commented
You want to try and add browser test that submits looooong value? Also how does it look visually when you are submitting long value?

2022-11-03 15:11 UTC, ckirksey3 commented
> Also how does it look visually when you are submitting long value?

If you try to type another character after reaching 10k, it just doesn't type. It's still possible for someone to inject a string larger than 10k into the dom and submit, but this prevents accidental failures.

2022-11-03 20:57 UTC, nbeloglazov requested changes

2022-11-03 20:57 UTC, nbeloglazov commented on browser-test/src/text.test.ts
> +        '1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
I suggest generating 10k string programmattically:

```
let str = '';
for (let i = 0; i < 1000; i++) {
  str += '123456789';
}
```

2022-11-03 21:26 UTC, ckirksey3 commented on browser-test/src/text.test.ts
> +        '1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
Good call. Updated!

2022-11-04 18:31 UTC, nbeloglazov approved these changes

2022-11-04 20:04 UTC, merged