Unify required question asterisk styling and fix screen-reader text
civiform/civiform pull request #3911
Opened 2022-12-10 00:12 UTC by jeanniefu

### Description

Updates the styling of the asterisk that represents required questions. Styling of the program blocks now matches program summary view.

Also updated the screenreader text so the asterisk is read out.

## Release notes

The title of the pull request will be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section.

### Checklist

#### General

- [ ] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

#### User visible changes

- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/application.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://docs.civiform.us/contributor-guide/developer-guide/feature-flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Issue(s) this completes

Fixes #<issue_number>; Fixes #<issue_number>...

2022-12-10 01:51 UTC, nbeloglazov requested changes
Update 'Release notes' in PR description

2022-12-10 01:51 UTC, nbeloglazov commented on server/app/views/applicant/ProgramIndexView.java
> +            false);
Can you add `/* addRequiredIndicator= */ false` ?

2022-12-10 01:51 UTC, nbeloglazov commented on server/app/views/questiontypes/ApplicantQuestionRendererImpl.java
> +                            false)))
Here too

2022-12-10 01:51 UTC, nbeloglazov commented on server/app/services/applicant/question/ApplicantQuestion.java
> +    return isOptional() ? getQuestionText() : getQuestionText() + " *";
Does screen reader reads "asterisk" when processing '*' ? is that convention among screenreader users and they understand what it means?

2022-12-11 23:35 UTC, shanemc-goog requested changes
looks good, just comment comments

2022-12-11 23:35 UTC, shanemc-goog commented on server/app/views/components/TextFormatter.java
> +            TextFormatter.createLinksAndEscapeText(line, UrlOpenAction.NewTab, false);
```suggestion
            TextFormatter.createLinksAndEscapeText(line, UrlOpenAction.NewTab, /*addRequiredIndicator= */ false);
```

2022-12-11 23:35 UTC, shanemc-goog commented on server/app/views/components/TextFormatter.java
> +      contentBuilder.add(span(" *").withClasses("text-red-600"));
Should this be a &nbsp  or is it okay to overflow to a new line?

2022-12-11 23:35 UTC, shanemc-goog commented on server/app/views/components/TextFormatter.java
>    public static ImmutableList<DomContent> createLinksAndEscapeText(
Would you mind javadocing this since it's public as well to be clear on the new param while you're here

2022-12-11 23:35 UTC, shanemc-goog commented on server/app/views/questiontypes/ApplicantQuestionRendererImpl.java
> +            question.getQuestionText(), TextFormatter.UrlOpenAction.NewTab, !question.isOptional());
```suggestion
            question.getQuestionText(), TextFormatter.UrlOpenAction.NewTab, /* addRequiredIndicator= */ 
 !question.isOptional());
```

2022-12-11 23:35 UTC, shanemc-goog commented on server/test/views/components/TextFormatterTest.java
> +            "hello google.com http://internet.website", TextFormatter.UrlOpenAction.SameTab, false);
```suggestion
            "hello google.com http://internet.website", TextFormatter.UrlOpenAction.SameTab, /*addRequiredIndicator= */ false);
```

2022-12-11 23:35 UTC, shanemc-goog commented on server/test/views/components/TextFormatterTest.java
> +            "hello google.com http://internet.website", TextFormatter.UrlOpenAction.NewTab, false);
```suggestion
            "hello google.com http://internet.website", TextFormatter.UrlOpenAction.NewTab, /*addRequiredIndicator= */ false);
```

2022-12-11 23:35 UTC, shanemc-goog commented on server/test/views/components/TextFormatterTest.java
> +            "hello google.com https://secure.website", TextFormatter.UrlOpenAction.SameTab, false);
```suggestion
            "hello google.com https://secure.website", TextFormatter.UrlOpenAction.SameTab, /*addRequiredIndicator= */ false);
```

2022-12-11 23:35 UTC, shanemc-goog commented on server/test/views/components/TextFormatterTest.java
> +            false);
```suggestion
            /*addRequiredIndicator= */ false);
```

2022-12-11 23:35 UTC, shanemc-goog commented on server/app/services/applicant/question/ApplicantQuestion.java
> +   * Get the question text that should be used for screen readers. We add a styled asterisk, which
```suggestion
   * Returns the question text that should be used for screen readers.
   *
   * <p>We add a styled asterisk, which
```

2022-12-11 23:35 UTC, shanemc-goog commented on server/app/services/applicant/question/ApplicantQuestion.java
> +   * Get the question text that should be used for screen readers. We add a styled asterisk, which
Gets is also correct, the phrasing just needs to read as if it was after "This method ..."

2022-12-16 22:11 UTC, shanemc-goog commented on server/app/services/applicant/question/ApplicantQuestion.java
> +   * <p>We add a styled asterisk, which
wrap this up too

2022-12-17 00:08 UTC, jeanniefu commented
Thanks for the reviews!

2022-12-17 02:08 UTC, nbeloglazov approved these changes

2022-12-17 02:27 UTC, shanemc-goog approved these changes

2022-12-17 02:27 UTC, merged