Update timezone of previously answered on text
civiform/civiform pull request #4037
Opened 2023-01-11 16:32 UTC by dkatzz

### Description

Using ZoneId.systemDefault() will show the timezone as GMT. By initializing the View with ZoneId and then calling this.zoneId, the zone is "America/Los_Angeles". This also seems to be how this is done in other files, so this seems consistent with other places where we localize a timestamp or date. 

It doesn't seem like there is currently a browser test that checks whether "previously answered state" is set correctly. I was thinking of filing a separate bug for that, but let me know if this seems in scope for this bug. 

## Release notes

The title of the pull request will be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section.

### Checklist

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

#### User visible changes

- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/application.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://docs.civiform.us/contributor-guide/developer-guide/feature-flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Issue(s) this completes

#3379

2023-01-11 22:23 UTC, bion approved these changes

2023-01-11 22:24 UTC, bion commented
> It doesn't seem like there is currently a browser test that checks whether "previously answered state" is set correctly. I was thinking of filing a separate bug for that, but let me know if this seems in scope for this bug.

best to handle than in a separate PR

2023-01-11 22:25 UTC, bion requested changes

2023-01-11 22:25 UTC, bion commented on server/app/views/applicant/ApplicantProgramSummaryView.java
> +      LocalDate date = Instant.ofEpochMilli(data.timestamp()).atZone(this.zoneId).toLocalDate();
suggestion (blocking): use [DateConverter](https://github.com/civiform/civiform/blob/main/server/app/services/DateConverter.java)

2023-01-13 17:27 UTC, dkatzz commented on server/app/views/applicant/ApplicantProgramSummaryView.java
> +      LocalDate date = Instant.ofEpochMilli(data.timestamp()).atZone(this.zoneId).toLocalDate();
Updated!

2023-01-14 03:42 UTC, bion approved these changes

2023-01-17 14:43 UTC, shanemc-goog approved these changes

2023-01-17 14:45 UTC, merged