Admin can configure address service area predicates
civiform/civiform pull request #4134
Opened 2023-01-31 04:02 UTC by bion

### Description

Extends the v2 predicate configuration UI to support address service area predicates. Released behind the `PREDICATES_MULTIPLE_QUESTIONS_ENABLED` feature flag.

### Checklist

#### General

- [ ] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [ ] Created tests which fail without the change (if possible)

#### New Features

- [ ] Conditioned new functionality on a [FeatureFlag](https://docs.civiform.us/contributor-guide/developer-guide/feature-flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Issue(s) this completes

Fixes https://github.com/civiform/civiform/issues/4046

2023-02-06 17:23 UTC, seanmalbert requested changes
@bion ,

I'm seeing that address service area validation visibility/eligibility only works properly when `predicates_multiple_questions_enabled = true`. If that feature flag isn't a requirement for setting address service area predicates then ProgramBlockPredicatesEditView needs further updates and if it is then the `IN_SERVICE_AREA` operator should be removed as an option from that view.

2023-02-06 22:49 UTC, seanmalbert requested changes
Comment (non-blocking): it seems like we're one new leaf expression node or scalar away from benefiting from some cleanup. Methods like getLeafNodes in PredicateGenerator are getting a little unwieldy in terms of test cases required for full coverage and human readability.

2023-02-06 23:03 UTC, bion commented on server/app/views/admin/programs/ProgramBlockPredicatesEditView.java
> +              .filter(scalar -> !scalar.equals(Scalar.SERVICE_AREA))
Good call

2023-02-06 23:04 UTC, bion commented on server/app/views/admin/programs/ProgramBlockEditView.java
> +                      blockDefinition,
Yeah, for consistency and also trying to prefer passing domain objects rather than primitives

2023-02-07 00:26 UTC, seanmalbert approved these changes

2023-02-07 00:40 UTC, merged