Separate out application.conf into smaller .conf files
civiform/civiform pull request #4302
Opened 2023-03-01 15:46 UTC by MichaelZetune

### Description

Refactors the very long `application.conf` file into smaller `.conf` files in a new `helper/` directory.

2023-03-01 15:53 UTC, MichaelZetune commented on server/conf/application.conf
> -## Akka
Now in `akka.conf`.

2023-03-01 15:54 UTC, MichaelZetune commented on server/conf/application.conf
> -## Secret key
Now in `secret-key.conf`.

2023-03-01 15:54 UTC, MichaelZetune commented on server/conf/application.conf
> -auth {
Now in `auth.conf`.

2023-03-01 15:56 UTC, MichaelZetune commented on server/conf/application.conf
> -## IDE
Now in `ide.conf`.

2023-03-01 15:56 UTC, MichaelZetune commented on server/conf/application.conf
> -## Internationalisation
Now in `internationalization.conf`.

2023-03-01 15:56 UTC, MichaelZetune commented on server/conf/application.conf
> -## Play HTTP settings
Now in `http.conf`.

2023-03-01 15:56 UTC, MichaelZetune commented on server/conf/application.conf
> -## WS (HTTP Client)
Now in `webservice.conf`.

2023-03-01 15:56 UTC, MichaelZetune commented on server/conf/application.conf
> -## Cache
Now in `cache.conf`.

2023-03-01 15:56 UTC, MichaelZetune commented on server/conf/application.conf
> -## Filter Configuration
Now in `filters.conf`.

2023-03-01 15:57 UTC, MichaelZetune commented on server/conf/application.conf
> -## Evolutions
Now in `database.conf`.

2023-03-01 15:57 UTC, MichaelZetune commented on server/conf/application.conf
> -## EBean
Now in `database.conf`.

2023-03-01 15:57 UTC, MichaelZetune commented on server/conf/application.conf
> -## AWS
Now in `cloud.conf`.

2023-03-01 15:57 UTC, MichaelZetune commented on server/conf/application.conf
> -## Durable Jobs
Now in `jobs.conf`.

2023-03-01 15:57 UTC, MichaelZetune commented on server/conf/application.conf
> -# esri address services
Now in `esri.conf`.

2023-03-01 15:58 UTC, MichaelZetune commented on server/conf/application.conf
> -# Common Intake Form flags
Now in `feature-flags.conf`.

2023-03-01 15:58 UTC, MichaelZetune commented on server/conf/application.conf
> -## Set cloud services
Now in `cloud.conf`.

2023-03-01 16:03 UTC, MichaelZetune commented
@avrittrohwer, I'm not sure how exactly to validate these changes aside from seeing that `bin/run-dev` still works. I don't see a validation mechanism in Play's docs:

https://www.playframework.com/documentation/2.0/Configuration

Do you know of a way to print out the final contents of `application.conf` so we can diff them before/after?

2023-03-01 18:08 UTC, avrittrohwer requested changes
Overall I think this is a good direction, I think having slightly less helper files may be a better balance for readability tho.

What if we consolidate akka, cache, filters, http, ide, modules, secret-key and webservice into a framework.conf?

2023-03-01 18:14 UTC, bion requested changes
I think splitting up some of the conf file could be helpful, but one thing I don't want to lose is the main application.conf file containing the things people will expect to find in it when reading the Play Framework docs, which suggests leaving framework-related conf items (i.e. everything nested under play, akka, database, db, filters, modules) in the main file. Otherwise I anticipate regular questions when people look for something they expect to find in that file and don't immediately see it.

2023-03-01 19:26 UTC, MichaelZetune commented
I've cleaned this up so that Play framework related vars remain in the main application.conf file.

I think the current state of this PR balances readability and modularity well now. Feel free to let me know if this PR doesn't make sense overall, though - happy to revert.

2023-03-01 19:32 UTC, avrittrohwer approved these changes
nit: put the ide.conf settings in application.conf

2023-03-01 19:45 UTC, MichaelZetune commented
> nit: put the ide.conf settings in application.conf

Done.

2023-03-01 20:10 UTC, bion approved these changes

2023-03-02 15:11 UTC, MichaelZetune commented
I checked out `main` and this branch and printed out the vars as suggested by @avrittrohwer, then piped them to a txt file. The diffs are here:

https://www.diffchecker.com/pZ0qLvFv/

Everything appears to check out on the vars themselves.

2023-03-02 15:12 UTC, merged