Change Buttons and add confirmation modal for guests on application confirmation page
civiform/civiform pull request #4500
Opened 2023-03-27 20:36 UTC by MichaelZetune

### Description

Please explain the changes you made here.

## Release notes

Adds a new modal to prompt guests to log in before applying to more programs.

### Checklist

#### General

- [x] Replace "All Done" and "Create account or sign in" with "Log in" and "Create Account"
- [x] Make "Apply to another program lead to a login prompt instead of straight back to the programs page
- [ ] Add screenshot test for new modal

![image](https://user-images.githubusercontent.com/30369272/228059483-05be8a21-f29c-4271-b278-5585358a4e80.png)

2023-04-03 21:18 UTC, gwendolyngoetz requested changes

2023-04-03 21:18 UTC, gwendolyngoetz commented on server/conf/messages
> +content.loginModalPrompt=You are not logged in to an account. Without an account you will not be able to edit an application, check the status of your application or apply for other benefits quickly.
Missing Oxford comma

```suggestion
content.loginModalPrompt=You are not logged in to an account. Without an account you will not be able to edit an application, check the status of your application, or apply for other benefits quickly.
```

2023-04-03 21:18 UTC, gwendolyngoetz commented on server/app/views/applicant/ApplicantUpsellCreateAccountView.java
> +    boolean hasEmailAddress = !Strings.isNullOrEmpty(account.getEmailAddress());
Is the email address check here to see if they already have an account? Is so, you probably want to be checking if the account has an authority_id instead.

2023-04-04 13:42 UTC, MichaelZetune commented on server/conf/messages
> +content.loginModalPrompt=You are not logged in to an account. Without an account you will not be able to edit an application, check the status of your application or apply for other benefits quickly.
Done.

2023-04-04 16:21 UTC, gwendolyngoetz approved these changes

2023-04-04 20:30 UTC, gwendolyngoetz approved these changes

2023-04-04 21:04 UTC, merged