Add tests for language files
civiform/civiform pull request #4516
Opened 2023-03-28 21:39 UTC by MichaelZetune

### Description

This PR adds some tests to enforce the following invariants on the language files:
* All keys in `messages` must be present in all other messages files
* An `IGNORE_LIST` is defined to enumerate exceptions to this rule. If a key is on the ignore list, it (1) must be in `messages` and (2) may not be in one or more other messages files.

Soon:
* We will enforce that the keys in `messages` and other messages files must be the *exact same* (except for the `IGNORE_LIST`), as opposed to the current state where the other language files just need to *have* those same keys. This involves changing `containsSubsequence` to `containsExactlyElementsOf`.
   * Currently, we cannot do this because there are keys that are present in some but not all other language files.

### Checklist

- [x] Created `test/conf/MessagesTest.java` as per description above.
- [x] Removed comments and empty lines from all non-primary language files.
- [x] Alphabetized keys in non-primary language files
   * While we would like to enforce this in the unit test, it is not possible because the Java `Properties` class reads in the keys into a HashMap. So we alphabetize them now and can maintain this on a best-effort basis.

2023-03-28 23:13 UTC, bion requested changes

2023-03-28 23:13 UTC, bion commented on bin/list-incomplete-messages
**issue (blocking):** It seems like this still provides value the java test doesn't yet: knowing which languages a given key is missing?

2023-03-28 23:13 UTC, bion commented on server/test/conf/MessagesTest.java
> +      Set.of(
**nitpick:** prefer immutable collections
```suggestion
      ImmutableSet.of(
```

2023-03-28 23:13 UTC, bion commented on server/test/conf/MessagesTest.java
> +          "conf/messages.zh-TW");
**suggestion (if-minor, non-blocking):** could glob here instead `conf/messages.*`

2023-03-28 23:13 UTC, bion commented on server/test/conf/MessagesTest.java
> +  String PRIMARY_LANGUAGE_FILE = "conf/messages";
**nitpick:** 
```suggestion
  private static final String PRIMARY_LANGUAGE_FILE = "conf/messages";
```

2023-03-28 23:13 UTC, bion commented on server/test/conf/MessagesTest.java
> +      // TODO(MichaelZetune): change containsSubsequence to containsExactlyElementsOf.
**nitpick:** reference an issue number please

2023-03-29 02:52 UTC, MichaelZetune commented on server/test/conf/MessagesTest.java
> +public class MessagesTest {
Done.

2023-03-29 02:53 UTC, MichaelZetune commented on server/test/conf/MessagesTest.java
> +  String PRIMARY_LANGUAGE_FILE = "conf/messages";
Done.

2023-03-29 02:53 UTC, MichaelZetune commented on server/test/conf/MessagesTest.java
> +      Set.of(
Done.

2023-03-29 02:55 UTC, MichaelZetune commented on server/test/conf/MessagesTest.java
> +      // TODO(MichaelZetune): change containsSubsequence to containsExactlyElementsOf.
Done.

2023-03-29 03:21 UTC, MichaelZetune commented on server/test/conf/MessagesTest.java
> +      assertThat(keysInForeignLangFile).containsSubsequence(keysInPrimaryFile);
Done, now it says a message like:

```
[error] Test conf.MessagesTest.testMessages failed: java.lang.AssertionError: [content.mobileFileUploadHelp, content.requiredFieldsAnnotation] found in primary language file but not in conf/messages.ko. Add these keys to conf/messages.ko to resolve this issue., took 0.218 sec
[error]     at conf.MessagesTest.testMessages(MessagesTest.java:86)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
```

2023-03-29 03:45 UTC, MichaelZetune commented on server/test/conf/MessagesTest.java
> +          "conf/messages.zh-TW");
Done.

2023-03-29 03:45 UTC, MichaelZetune commented on bin/list-incomplete-messages
I believe I've added this value to the Java test now; let me know if you disagree.

2023-03-29 03:53 UTC, MichaelZetune commented on bin/list-incomplete-messages
Edit: well, you can't *give* the test a key and ask what files are missing it, but it's pretty close with the error message. Let me know if that's not close enough and you prefer to keep the script.

2023-03-29 17:00 UTC, MichaelZetune commented on bin/list-incomplete-messages
I've updated the test to use `@Parameters`, so we run one test per file. Now we get output like this (one key missing from one file and another key missing from another file):

```
[error] Test conf.MessagesTest.messages_keysInPrimaryFileInAllOtherFiles(conf/messages.es-US) [2] failed: java.lang.AssertionError: [button.deleteFile] found in primary language file but not in conf/messages.es-US. Add these keys to conf/messages.es-US or to the ignore list in conf.MessagesTest to resolve this issue., took 0.008 sec
[error]     at conf.MessagesTest.messages_keysInPrimaryFileInAllOtherFiles(MessagesTest.java:85)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
[info] Test conf.MessagesTest.messages_keysInPrimaryFileInAllOtherFiles(conf/messages.ko) [3] started
[info] Test conf.MessagesTest.messages_keysInPrimaryFileInAllOtherFiles(conf/messages.so) [4] started
[error] Test conf.MessagesTest.messages_keysInPrimaryFileInAllOtherFiles(conf/messages.so) [4] failed: java.lang.AssertionError: [content.or] found in primary language file but not in conf/messages.so. Add these keys to conf/messages.so or to the ignore list in conf.MessagesTest to resolve this issue., took 0.002 sec
[error]     at conf.MessagesTest.messages_keysInPrimaryFileInAllOtherFiles(MessagesTest.java:85)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
```

2023-03-29 18:31 UTC, bion approved these changes

2023-03-29 18:31 UTC, merged