Add support for publishing a single program.
civiform/civiform pull request #4813
Opened 2023-05-09 16:21 UTC by reemaka

### Description

Please explain the changes you made here.

## Release notes

The title of the pull request will be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section.

### Checklist

#### General

- [ ] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

#### User visible changes

- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/application.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://docs.civiform.us/contributor-guide/developer-guide/feature-flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Issue(s) this completes

Fixes #<issue_number>; Fixes #<issue_number>...

2023-05-10 21:02 UTC, bion requested changes

2023-05-10 21:02 UTC, bion commented on server/app/views/admin/programs/ProgramIndexView.java
> +        draftRowExtraActions.add(renderPublishProgramLink(draftProgram.get(), request));
**suggestion (non-blocking):** (you mention that the UI is tentative and this is feature flagged so this is non-blocking) could disable the button if the program has modified questions shared with other programs

2023-05-10 21:02 UTC, bion commented on server/conf/helper/feature-flags.conf
> +publish_single_program_enabled = ${?PUBLISH_SINGLE_PROGRAM_ENABLED}
**nitpick:** missing newline at end of file

2023-05-10 23:26 UTC, reemaka commented on server/app/repository/VersionRepository.java
> +      transaction.end();
Nope, added a comment to explain (well, copied a comment from getDraftVersion)

2023-05-11 21:49 UTC, reemaka commented on server/app/repository/VersionRepository.java
> +          programToPublish.isPresent(), "Program being published not found in Draft.");
Done

2023-05-11 21:49 UTC, reemaka commented on server/app/repository/VersionRepository.java
> +              .collect(ImmutableSet.toImmutableSet());
Done

2023-05-11 21:49 UTC, reemaka commented on server/app/repository/VersionRepository.java
> +                          && referencingDraftProgramsByQuestionName.get(questionName).size() > 1);
Done

2023-05-11 21:49 UTC, reemaka commented on server/app/repository/VersionRepository.java
> +      newDraft.refresh();
Done

2023-05-11 21:49 UTC, reemaka commented on server/app/repository/VersionRepository.java
> +      publishNewSynchronizedVersion(programToPublishAdminName);
Done

2023-05-11 21:49 UTC, reemaka commented on server/app/services/program/CantPublishProgramWithSharedQuestionsException.java
> +public class CantPublishProgramWithSharedQuestionsException extends Exception {
Done

2023-05-11 21:51 UTC, bion commented on server/app/repository/VersionRepository.java
> +   * @throws CantPublishProgramWithSharedQuestionsException if any of the program's modified
oh, thanks!

2023-05-11 21:53 UTC, bion commented on server/app/repository/VersionRepository.java
> +   * @throws CantPublishProgramWithSharedQuestionsException if any of the program's modified
thanks!

2023-05-11 21:54 UTC, bion approved these changes

2023-05-12 13:55 UTC, merged