Add validation for question names that would create path conflicts.
civiform/civiform pull request #4991
Opened 2023-05-31 20:07 UTC by reemaka

### Description

Temporary mitigation for #4178. Characters that are not alphabetic or spaces get stripped out of the name for the question path, creating confusing conflicts. While eventually we may want to allow such characters in paths, this improves the experience in the meantime:
1. Adds a requirement that the admin name contains only letters and spaces, showing an error message if validation fails.
2. Rewords the error that is displayed when a question path conflicts with an existing question to hopefully be easier to understand. Previously, the error mentioned the question ID which the admin doesn't have much visibility into.

## Release notes

### Checklist

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [x] Created tests which fail without the change (if possible)

### Issue(s) this completes

Part of #4178

2023-05-31 20:33 UTC, gwendolyngoetz requested changes

2023-05-31 20:33 UTC, gwendolyngoetz commented on server/app/services/question/types/QuestionDefinition.java
> +    if (!name.matches("^[a-zA-Z ]*$")) {
Can you put the regex string in a constant called VALID_QUESTION_NAME_CHARACTERS or something of that ilk?

2023-06-01 15:17 UTC, gwendolyngoetz approved these changes

2023-06-01 15:31 UTC, gwendolyngoetz approved these changes

2023-06-01 16:05 UTC, gwendolyngoetz approved these changes

2023-06-01 23:49 UTC, reemaka commented
Scaled this back to just making the error message clearer. Validating the question name was causing all of the browser tests that set question names to break. I thought about allowing characters like hyphens and underscores instead, but if we update the path creation logic, it will affect how things are stored in the database so I didn't want to do that.

2023-06-02 15:26 UTC, merged