Cleanup unused accounts
civiform/civiform pull request #5742
Opened 2023-10-06 00:03 UTC by bion

### Description

Please explain the changes you made here.

## Release notes

The title of the pull request will be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section.

### Checklist

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [ ] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release | database >
- [ ] Created unit and/or browser tests which fail without the change (if possible)
- [ ] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary

#### User visible changes

- [ ] Followed steps to [internationalize new strings](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#internationalization-for-application-strings)
- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/helper/feature-flags.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://github.com/civiform/civiform/wiki/Feature-Flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Instructions for manual testing

If instructions are needed for manual testing by reviewers, include them here.

### Issue(s) this completes

Fixes #<issue_number>; Fixes #<issue_number>...

2023-10-10 16:42 UTC, gwendolyngoetz requested changes
Deleting these unused guest accounts is great. Since there is no actual data I don't see any retention issues from my end. If it's possible other municipalities have different requirements in keeping even empty records we may need to make this something that can be disabled for each deployment.

2023-10-10 21:07 UTC, bion commented on server/app/repository/AccountRepository.java
> +    return database.sqlUpdate(sql).execute();
It's all done in a single statement, which creates an implicit transaction in postgres: https://www.postgresql.org/docs/current/tutorial-transactions.html#:~:text=PostgreSQL%20actually%20treats%20every%20SQL,sometimes%20called%20a%20transaction%20block.

2023-10-10 21:08 UTC, bion commented on server/app/repository/AccountRepository.java
> +            + "WHERE accounts.id IN (SELECT account_id FROM unused_accounts);";
My intention here is to do both deletes in a single statement, having `applicants_deleted` is just an artifact of trying to do that. How would using a temp table work?

2023-10-10 21:19 UTC, bion commented
@gwendolyngoetz 

> If it's possible other municipalities have different requirements in keeping even empty records we may need to make this something that can be disabled for each deployment.

Sent an email asking about this.

2023-10-10 21:44 UTC, gwendolyngoetz commented on server/app/repository/AccountRepository.java
> +            + "WHERE accounts.id IN (SELECT account_id FROM unused_accounts);";
I think what was throwing me off was difference between how older version of Microsoft Sql Server CTEs worked. I see [Postgres docs](https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-MODIFYING) having a similar example to what you have so not an issue anymore.

-----
Providing the rest to answer the question of how a temp table would work

```sql
SELECT applicants.account_id AS account_id, applicants.id AS applicant_id 
INTO TEMP unused_accounts
FROM applicants
LEFT JOIN applications ON applicants.id = applications.applicant_id 
LEFT JOIN accounts ON accounts.id = applicants.account_id 
WHERE applications.applicant_id IS NULL 
AND accounts.authority_id IS NULL 
AND applicants.when_created < CURRENT_DATE - INTERVAL '90 days';

DELETE FROM applicants
WHERE applicants.id IN (SELECT applicant_id FROM unused_accounts);
	
DELETE FROM accounts 
WHERE accounts.id IN (SELECT account_id FROM unused_accounts);
```

2023-10-23 21:46 UTC, bion commented
Have gotten written approval from civic entities

2023-10-23 22:37 UTC, gwendolyngoetz approved these changes

2023-10-24 17:25 UTC, bion commented on server/app/durablejobs/jobs/UnusedAccountCleanupJob.java
> +  private static final int UNUSED_ACCOUNT_MAX_AGE_IN_DAYS = 90;
great point 😂

2023-10-24 17:51 UTC, merged