Manage applicant autofocus
civiform/civiform pull request #5949
Opened 2023-11-09 00:22 UTC by bion

### Description

Please explain the changes you made here.

## Release notes

The title of the pull request will be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section.

### Checklist

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [ ] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release | database >
- [ ] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).
- [ ] Created unit and/or browser tests which fail without the change (if possible)
- [ ] Performed manual testing (Chrome and Firefox if it includes front-end changes)
- [ ] Extended the README / documentation, if necessary

#### User visible changes

- [ ] Followed steps to [internationalize new strings](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#internationalization-for-application-strings)
- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/helper/feature-flags.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://github.com/civiform/civiform/wiki/Feature-Flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Instructions for manual testing

If instructions are needed for manual testing by reviewers, include them here.

### Issue(s) this completes

Fixes #<issue_number>; Fixes #<issue_number>...

2023-11-10 01:20 UTC, bion commented on browser-test/image_snapshots/date_test/date.png
I can't find the diff here 🤷🏻‍♂️

2023-11-13 16:23 UTC, rockycodes requested changes
Overall this looks great! Really clever solution to focus on specific fields within questions. I have some questions/comments around clarity, but the overall approach lgtm and works great.

2023-11-13 16:23 UTC, rockycodes commented on server/app/views/applicant/ApplicantProgramBlockEditView.java
> +      return ordinalErrorCount == 1
Ah I understand, it increments for each question with an error, but we only ever want it to focus on the first question with an error.

2023-11-13 16:23 UTC, rockycodes commented on server/app/views/questiontypes/ApplicantQuestionRendererParams.java
> +  /** True if autofocus is FIRST_ERROR. */
Ah I think I'm understanding. `FIRST_FIELD` is set when an applicant clicks on the question from the review screen, is that right? So `autoFocusFirstField` is used to check if they clicked on the question. `autofocusFirstError` is used to find the first error on the page. Am I understanding this right?

2023-11-13 16:23 UTC, rockycodes commented on server/app/views/questiontypes/ApplicantQuestionRendererParams.java
> +  /** True if questions that only have a single question should autofocus it. */
Reading through the code more, I think this is a convenience method for question types that only have one field (eg. text), so we don't need to determine which field _within_ the question should be focused on. I recommend changing this comment to something like "True if a question with only one field should be autofocused".

2023-11-13 17:37 UTC, melanie-exygy commented on server/app/controllers/applicant/ApplicantProgramBlocksController.java
> +        .setApplicantSelectedQuestionName(questionName);
praise:  This is a nice clarification.

2023-11-13 17:50 UTC, bion commented on server/app/views/applicant/ApplicantProgramBlockEditView.java
> +      return ordinalErrorCount == 1
Yep!

2023-11-13 17:54 UTC, bion commented on server/app/views/questiontypes/ApplicantQuestionRendererParams.java
> +  /** True if questions that only have a single question should autofocus it. */
woops! Yep, the comment didn't make any sense as written. Updated.

2023-11-13 17:55 UTC, bion commented on server/app/views/questiontypes/ApplicantQuestionRendererParams.java
> +  /** True if autofocus is FIRST_ERROR. */
> Ah I think I'm understanding. FIRST_FIELD is set when an applicant clicks on the question from the review screen, is that right? So autoFocusFirstField is used to check if they clicked on the question. autofocusFirstError is used to find the first error on the page. Am I understanding this right?

Yes.

These are just convenience methods to make the code that consumes this data a little cleaner.

2023-11-13 17:55 UTC, bion commented on server/app/views/questiontypes/ApplicantQuestionRendererParams.java
> +    // Autofocus the first field that has a validation error message
Yes

2023-11-13 17:57 UTC, bion commented on server/test/views/applicant/ApplicantProgramBlockEditViewTest.java
> +  // While mocking is generally discouraged, some tests in this file don't need c'tor so mocking
https://medium.com/@queenskisivuli/why-mocking-data-is-a-bad-practice-for-testing-a20d2d7104aa

2023-11-13 17:58 UTC, bion commented on server/test/views/applicant/ApplicantProgramBlockEditViewTest.java
> +  // While mocking is generally discouraged, some tests in this file don't need c'tor so mocking
IMO mocking in unit tests is usually the result of poor object design. We could probably make some improvements to the organization of the code here but it's beyond the scope of this PR.

2023-11-13 17:59 UTC, melanie-exygy commented
Testing on your branch and, unfortunately, focus only goes to the desired field sometimes.  It is very inconsistent, as it was before.  This is a screen recording of when I click on a question from the summary page, but I saw the same issue with field validation errors.
https://github.com/civiform/civiform/assets/134556723/0133b8b3-e0b9-4733-8cb1-b3f3f91cf50e

2023-11-13 18:01 UTC, bion commented on server/test/views/applicant/ApplicantProgramBlockEditViewTest.java
> +  public void calculateAutoFocusTarget_formHasErrors_displayErrors_isSecondQuestionWithErrors() {
I don't know that we have a convention, I don't mind describing the expectation in the test name though. Updated.

2023-11-13 20:06 UTC, rockycodes commented on server/app/views/questiontypes/ApplicantQuestionRendererParams.java
> +  /** True if autofocus is FIRST_ERROR. */
Ok cool. What do you think about explaining that more in these comments? Something like "Will be true for the first field of the question an applicant selected from the review page" and "Will be true for the first field of the first question on the page that has an error".

2023-11-13 20:08 UTC, rockycodes commented on server/app/views/questiontypes/ApplicantQuestionRendererParams.java
> +    // Autofocus the first field that has a validation error message
👍 I suggest adding that in here for clarity since the comment below has "first field in the question"

2023-11-13 20:08 UTC, rockycodes commented on server/test/views/applicant/ApplicantProgramBlockEditViewTest.java
> +  // While mocking is generally discouraged, some tests in this file don't need c'tor so mocking
Thank you for explaining!

2023-11-22 01:30 UTC, bion commented
Investigated offline, @melanie-exygy determined this improves focus behavior for non-voiceover screen reader users by focusing the specific input with validation errors.

2023-11-22 15:46 UTC, rockycodes commented on server/test/views/applicant/ApplicantProgramBlockEditViewTest.java
> +  public void calculateAutoFocusTarget_formHasErrors_displayErrors_isSecondQuestionWithErrors() {
Ty! I find this much easier to parse.

2023-11-22 15:48 UTC, rockycodes approved these changes

2023-11-22 21:24 UTC, bion commented on server/app/views/questiontypes/ApplicantQuestionRendererParams.java
> +  /** True if autofocus is FIRST_ERROR. */
Done

2023-11-22 21:24 UTC, bion commented on server/app/views/questiontypes/ApplicantQuestionRendererParams.java
> +    // Autofocus the first field that has a validation error message
Done

2023-11-23 01:52 UTC, merged